### ISSUE TITLE
请问线性方程组求解打算哪个库，或者是自己开发？

### ISSUE THREAD

**Issue by wphu** [weihuayi/openfinite#1]

**Comment by weihuayi** [comment]
线性方程组求解会自己开发，但也会利用 Eigen 等这些开源的包。

**Comment by wphu** [comment]
如果成都超算开发的chipsum性能不错的话也可以用他们的。

另外，请问魏老师，国内有没有自己开发网格生成软件的？类似gmsh tetgen那种？你觉得这个难不难

**Comment by weihuayi** [comment]
是的, 求解器会先用已有的, 自己再根据需要针对性的开发一些.&nbsp;&nbsp;


国内有开发网格生成软件的, 如浙江大学, 北京大学等都有, 但基本都是闭源的, 外人一般看不到.&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Dec 24, 2021 03:21 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [weihuayi/openfinite] 请问线性方程组求解打算哪个库，或者是自己开发？ (Issue #1)

&nbsp;



 
如果成都超算开发的chipsum性能不错的话也可以用他们的。
 
另外，请问魏老师，国内有没有自己开发网格生成软件的？类似gmsh tetgen那种？你觉得这个难不难
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wphu** [comment]
好的，多谢了。
